/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:8aa2e087-4623-406e-91ff-aac1281cbce4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_StXr1YDqT",
    "aws_user_pools_web_client_id": "27uqlu5636de1nab65hhqmguus",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lys64zqep5cypkcp2lhdcrew4i.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lpgfvaszojb3zbs5eimccukuta",
    "aws_user_files_s3_bucket": "amplifyapp18854813b0137450c90f23fa5b370a63b163718-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
